version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "10:00"
    target-branch: development
  - package-ecosystem: "docker"
    directory: "/src/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "10:00"
    target-branch: development
  - package-ecosystem: pip
    directory: "/test"
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
    open-pull-requests-limit: 10
    target-branch: development
