version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "10:00"
    target-branch: dev
    reviewers:
      - "pi-hole/docker-maintainers"
  # Maintain dependencies for GitHub Actions development-v6
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "10:00"
    target-branch: development-v6
    reviewers:
      - "pi-hole/docker-maintainers"
