name: Codespell
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  spell-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
    -
      name: Spell-Checking
      uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 #v2.2
      with:
        ignore_words_file: .codespellignore
