name: Editorconfig-Checker
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  editorconfig-checker:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

    - name: Get editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@4b6cd6190d435e7e084fb35e36a096e98506f7b9 # tag v2. is really out of date

    - name: Run editorconfig-checker
      run: editorconfig-checker
